// Generated from the C# compiler (DesignCompiler.cs, TemplateRuntime.cs) — the scripts a compiled page carries.
// Kept byte-identical to the server's; the parity tests fail if they drift. Regenerate with
// testing/generate-scripts.py rather than editing.

export const DETECT_SCRIPT = "if(!(window.CSS&&CSS.supports&&CSS.supports('animation-timeline: scroll()')))document.documentElement.classList.add('ib-fb')";

export const FALLBACK_SCRIPT = "(function(){var d=document.documentElement;if(!d.classList.contains('ib-fb'))return;\nvar els=[].slice.call(document.querySelectorAll('[data-ts]')),u=1,q=0;\nfunction size(){u=Math.min(window.innerWidth||390,480)/390;}\nfunction each(el,p){var list=[el,el.firstElementChild];for(var i=0;i<list.length;i++){var n=list[i];if(!n||!n.getAnimations)continue;var a=n.getAnimations();for(var j=0;j<a.length;j++){try{a[j].pause();a[j].currentTime=p*1000;}catch(e){}}}}\nfunction run(){q=0;var y=(window.pageYOffset||0)/u;for(var i=0;i<els.length;i++){var el=els[i],s=+el.getAttribute('data-ts'),e=+el.getAttribute('data-te'),p=e>s?(y-s)/(e-s):0;each(el,p<0?0:p>1?1:p);}}\nfunction tick(){if(!q)q=requestAnimationFrame(run);}\nsize();run();addEventListener('scroll',tick,{passive:true});addEventListener('resize',function(){size();tick();});})();";

export const EDITOR_SCRIPT = "(function(){function u(){return Math.min(window.innerWidth||390,480)/390;}\nvar want=null;window.scrollTo(0,__SCROLL__*u());\naddEventListener('message',function(e){var m=e.data||{};if(m.type==='ib:scroll'){want=(+m.y||0)*u();window.scrollTo(0,want);}});\nvar f=0;addEventListener('scroll',function(){if(f)return;f=requestAnimationFrame(function(){f=0;var y=window.pageYOffset,ours=want!==null&&Math.abs(y-want)<1.5;want=null;if(ours)return;parent.postMessage({type:'ib:scrolled',y:y/u()},'*');});},{passive:true});\nparent.postMessage({type:'ib:ready',y:window.pageYOffset/u()},'*');})();";

export const TEMPLATE_RUNTIME = "(function () {\n  'use strict';\n  // The payload is still inlined so a template's own script can read it, even though nothing\n  // here binds it. Same event and same shape the injector raised.\n  var el = document.getElementById('invite-data');\n  var data = {};\n  try { data = JSON.parse((el && el.textContent) || '{}'); } catch (e) { data = {}; }\n  try {\n    window.invite = window.invite || {};\n    window.invite.data = data;\n    window.dispatchEvent(new CustomEvent('invite:data', { detail: data }));\n  } catch (e) {}\n\n  var sections = [];\n  var envelope = null;\n\n  // Scroll position as a CSS custom property, so a template can scrub an animation in plain\n  // CSS — calc(var(--ib-progress) * …) — without writing a scroll handler of its own.\n  function publish(p) {\n    document.documentElement.style.setProperty('--ib-progress', p.toFixed(4));\n    try {\n      window.invite.progress = p;\n      window.dispatchEvent(new CustomEvent('invite:progress', { detail: p }));\n    } catch (e) {}\n  }\n\n  // Position-based rather than IntersectionObserver: a fast or programmatic scroll can never\n  // \"skip\" a section and leave it stuck invisible.\n  function revealInView() {\n    var vh = window.innerHeight || document.documentElement.clientHeight || 0;\n    for (var i = 0; i < sections.length; i++) {\n      var s = sections[i];\n      if (s.__ibShown) continue;\n      if (s.getBoundingClientRect().top < vh * 0.9) {\n        s.classList.add('ib-visible', 'is-visible');\n        s.__ibShown = true;\n      }\n    }\n  }\n\n  function start() {\n    sections = Array.prototype.slice.call(\n      document.querySelectorAll('.ib-section, [data-reveal]'));\n    envelope = document.querySelector('.ib-envelope, [data-envelope]');\n    revealInView(); // whatever is already on screen\n    publish(0);\n    window.addEventListener('scroll', function () {\n      revealInView();\n      var max = (document.documentElement.scrollHeight || 0) - window.innerHeight;\n      publish(max > 0 ? window.scrollY / max : 0);\n      if (envelope && window.scrollY > window.innerHeight * 0.25) {\n        envelope.classList.add('ib-opened', 'is-open');\n      }\n    }, { passive: true });\n  }\n\n  if (document.readyState === 'loading') {\n    document.addEventListener('DOMContentLoaded', start);\n  } else {\n    start();\n  }\n})();";
